### ISSUE TITLE
How can I make payment using this plugin like Credit Card, Apple Pay, Google Pay etc.?

### ISSUE THREAD

**Issue by shrigalok** [jeremiahlukus/authorize_net_plugin#1]

**Comment by jeremiahlukus** [comment]
@AlokMishra01 this is a wrapper for authorize.net. It wraps their mobile SDK's 
https://github.com/AuthorizeNet/accept-sdk-ios
https://github.com/AuthorizeNet/accept-sdk-android


This doesn't  process payments it gives you a token so you don't pass credit card information to your backend sever.


This is not for in-app-purchases both apple and google will reject your app if you use anything other than their payment system to take in app purchases. If you are wanting to do this use 

https://pub.dev/packages/in_app_purchase  
I also use 
https://pub.dev/packages/flutter_inapp_purchase  
With it to clear pending transactions.
