### ISSUE TITLE
zipCode should be made optional

### ISSUE THREAD

**Issue by Okiring** [jeremiahlukus/authorize_net_plugin#10]
Currently it appears one is forced to add a valid zip code when requesting a nonce however this is not mandatory in the SDK.  Before migrating to null-safety this was fine but after the upgrade to sound null safety its required..Thea are some cases where one might not require a zip code.

**Comment by jeremiahlukus** [comment]
You are correct 

```
                                               .cvvCode(CARD_CVV) // Optional
                                               .zipCode(ZIP_CODE) // Optional
                                               .cardHolderName(CARD_HOLDER_NAME)  // Optional
```

**Comment by jeremiahlukus** [comment]
This should be an easy PR, I have a new work computer and have to catch up on on other stuff. If you need this now then please submit a PR and i will publish. You can add a new test removing those fields so in the future we know they are supposed to be optional. 

If you are unable to send a PR I can get to it next week.

**Comment by Okiring** [comment]
@jeremiahlukus did u ever solve this issue?

**Comment by jeremiahlukus** [comment]
I didn’t add this, while I review the recent PR  I can add this as well

**Comment by Okiring** [comment]
Okay..That will be great

**Comment by jeremiahlukus** [comment]
Actually it seems zip it required somewhere is the authorize net sdk. When i remove it the request fails.
