### ISSUE TITLE
Questions !

### ISSUE THREAD

**Issue by DevPlus31** [jeremiahlukus/authorize_net_plugin#11]
Is the process only uses AuthorizeNet servers, 
How can I update my server with payment process result in order to deliver the service and generate an invoice?

Also is it possible to use payment Profile form mobile app? 

Thank you.

**Comment by jeremiahlukus** [comment]
this is a wrapper for the ios and android AuthorizeNet plugin it does not do anything outside of what those plugins do.

**Comment by DevPlus31** [comment]
Thanks. I think I will do it on the server side.

**Comment by jeremiahlukus** [comment]
Let me know if there are issues with the package though. Sorry for the late response house was hit by a tornado have some issues to take care of still but I’ll try to get back to you within a couple days next time.

**Comment by DevPlus31** [comment]
I hope you're fine by now and things get better for you and your family.
