### ISSUE TITLE
How can I generete token for Apple pay and Google pay to make payment from backend server.

### ISSUE THREAD

**Issue by shrigalok** [jeremiahlukus/authorize_net_plugin#2]
I am developing an application that uses Authorize.net payment to buy products that are not in-app service but they also want to integrate Apple pay and Google pay to buy products how can I do this.

**Comment by jeremiahlukus** [comment]
First you should read the guidelines from apple and google to make sure you can use an outside payment system. 

If you can, then these would be separate. You have some payments going through the app store/ play store and some going through authorize.net. 

What i do personally is use authorize.net for web only and then the stores from mobile application. I use 
flutter_inapp_purchase, and in_app_purchase

**Comment by jeremiahlukus** [comment]
Closing this as its not an issue with the plugin
