### ISSUE TITLE
How to store card information and pull that information for next payment?

### ISSUE THREAD

**Issue by UsamaKarim** [jeremiahlukus/authorize_net_plugin#4]
Hi, Thanks for your work.
I want to implement authorize in my app with the features of storing information of cards of customers on authorize servers so that my user doesn't need to add it again for their next purshase?

**Comment by jeremiahlukus** [comment]
Hey that’s not really a question. 

By your statement of you want to not store any credit card info you need to store the auth net customer profile Id and customer payment profile id if you have subscriptions you need to store the subscription Id as well.

**Comment by jeremiahlukus** [comment]
https://developer.authorize.net/api/reference/index.html


here is the docs for auth net 👍

**Comment by UsamaKarim** [comment]
> https://developer.authorize.net/api/reference/index.html
> 
> here is the docs for auth net 👍

But I can't do this with this package. Right?

**Comment by jeremiahlukus** [comment]
https://github.com/AuthorizeNet/accept-sdk-ios

https://github.com/AuthorizeNet/accept-sdk-android


this app wraps these 2 packages so everything you can do in these can be done in this.

**Comment by jeremiahlukus** [comment]
And yes that is what I do as well. I do not store credit card information in my database I store the 3 datapoints I mentioned above.

**Comment by UsamaKarim** [comment]
> [AuthorizeNet/accept-sdk-ios](https://github.com/AuthorizeNet/accept-sdk-ios)
> 
> [AuthorizeNet/accept-sdk-android](https://github.com/AuthorizeNet/accept-sdk-android)
> 
> this app wraps these 2 packages so everything you can do in these can be done in this.

I find out that these packages are rarely updated even though these are official. Are these fully stable and will work under the hood without any problem?

**Comment by UsamaKarim** [comment]
> And yes that is what I do as well. I do not store credit card information in my database I store the 3 datapoints I mentioned above.

Do you connect your app with the REST API? If we use REST API, Is there any problem while publishing the app to Playstore/Appstore?

**Comment by jeremiahlukus** [comment]
Yes I do, I have my own api with a db to store that info, and no there isn’t an issue as long as you following the App Store guidelines. Basically if you are giving physical goods you can use this. With a few exception most everything else you need to use the google play or App Store to make purchases. You would need to look into each of the stores you want to be on and read their guidelines.

**Comment by UsamaKarim** [comment]
> Yes I do, I have my own api with a db to store that info, and no there isn’t an issue as long as you following the App Store guidelines. Basically if you are giving physical goods you can use this. With a few exception most everything else you need to use the google play or App Store to make purchases. You would need to look into each of the stores you want to be on and read their guidelines.

The app is already on Playstore/Appstore with stripe payments. But my client wants to implement Authorize in the app. I told him that the Authorize SDK is not available for flutter and I am not aware of Android/iOS native. 

Then I find out your work but unfortunately, this wrapper doesn't have all the features of the Authorize. I have only fear of not having the app PCI compliant if I use REST API.

**Comment by jeremiahlukus** [comment]
The rest api doesn’t make the request to auth net it’s stores id’s from the response as associates it with a user. The application pings auth net directory then sends the response ids to the api. 

Have you tried to use this library? 
Do you have any issues with using it? 
I am using it for 2 applications and have no issues I know 2 other people are using it as well. If this is lacking a feature then what is it lacking? This creates a payment token to send to auth net so you don’t sent plain credit card information over http. Please follow the example in the application and in the readme

**Comment by UsamaKarim** [comment]
> Have you tried to use this library? 

I am going to implement in couple of days.
> If this is lacking a feature then what is it lacking?
 
Sorry for cross questioning. Does it have all features from native SDKs? I found that the only method available is getting the token inside whole package.

> This creates a payment token to send to auth net so you don’t sent plain credit card information over http. Please follow the example in the application and in the readme

Yes that's what I need. My only concern is to keep application PCI compliance. I checked that you are wrapping SDKs for getting token.

**Comment by jeremiahlukus** [comment]
Yes the native sdk’s do one thing, they give you an accept payment token for you to use in your POST request to authorize net. So this gives you a token then you use auth nets rest api to finish the transaction with the token. Yes to my knowledge it’s PCI compliant but if you wanted to ask more you can ask on the auth net form since my library is literally a wrapper around the sdk it has no other functionality. 

Im open to expand the functionality of this lib but I just used dio in my applications to make the requests and preferred to keep all of that out of this package. Maybe if I have another application I’ll create more methods.

**Comment by UsamaKarim** [comment]
> Im open to expand the functionality of this lib but I just used dio in my applications to make the requests and preferred to keep all of that out of this package. Maybe if I have another application I’ll create more methods.

I wish if I could contribute to your work but sadly, I freshly started with flutter, and for now not thinking to learn native development

**Comment by jeremiahlukus** [comment]
Ok going to close this, when you start using it and there is an issue please open another.

**Comment by UsamaKarim** [comment]
Hi,

Can you please show me an example of how do you work with customer profiles and make a transaction with your package? Your help will be much appreciated.

**Comment by UsamaKarim** [comment]
@jeremiahlukus 

Kindly confirm the steps involved in the implementation.

New Customer
Step 1. Get Merchant Details (To get `clientId`/ `publicClientKey `)
Step 2. Call `AuthorizeNetPlugin.authorizeNetToken()` from the package
Step 3. POST request `createTransactionRequest` for making a transaction.

My Question?

When should I create a customer profile?
