### ISSUE TITLE
Getting stuck in async call when card details are wrong

### ISSUE THREAD

**Issue by neel-sharma** [jeremiahlukus/authorize_net_plugin#5]
Scenarios where we enter a too long CVV. We get CVV Invalid error message in logs. But the app gets stuck in the await call. Need an exit. I'd suggest you add a callback in such scenarios where we are not getting proper response from the backend, so that we can easily distinguish between the success message and the failures.

**Comment by jeremiahlukus** [comment]
Looking into this I’ll push a fix in the next couple days. I’ll add some tests in the package to test this as well. I have form validators in my app so i never came across this error.

**Comment by UsamaKarim** [comment]
I am using `flutter_credit_card` package for validation, But I came across the same issue, Actually, the problem is not with the CVV code, As I am getting this error only on Android, if any of the card details are wrong the callback is infinite. The package gives an error but the callback never ends.
```
I[/System.out]()(17720): Please provide valid credit card number.
```
You can try with following Card number with any expiration date and CVV code on Android.
1900 3028 2665 3027

**Comment by jeremiahlukus** [comment]
I’ve been pretty slammed at work the last couple months I am happy to accept a PR to fix this issue though. If not it might be another couple weeks before I can get time to do it.

**Comment by UsamaKarim** [comment]
> Scenarios where we enter a too long CVV. We get CVV Invalid error message in logs. But the app gets stuck in the await call. Need an exit. I'd suggest you add a callback in such scenarios where we are not getting proper response from the backend, so that we can easily distinguish between the success message and the failures.

try to catch `PlatformException`. It does the job for me.

**Comment by jeremiahlukus** [comment]
Yea since this is just a wrapper for the auth net plugin i dont really want to go beyond that. 

You can make a PR though if this is something you really wanted I would merge it in as its not a bad thing.
