### ISSUE TITLE
[Feature Request] Allow creating and accessing customer profile/payment profile

### ISSUE THREAD

**Issue by UsamaKarim** [jeremiahlukus/authorize_net_plugin#6]
Hi, @jeremiahlukus 

As we discussed before in the previous issue, I want to create a customer profile, so the customer does not need to put his payment information again & again.

### Main issue
Creating a customer profile need to send the information over HTTP. As shown in the example in the documentation of Authorize.Net. [https://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-payment-profile](https://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-payment-profile) 

```
{
  "createCustomerPaymentProfileRequest": {
      "merchantAuthentication": {
    "name": "API-KEY",
    "transactionKey": "TRANSACTION-KEY"
  },
    "customerProfileId": "10000",
    "paymentProfile": {
      "billTo": {
        "firstName": "John",
        "lastName": "Doe",
        "address": "123 Main St.",
        "city": "Bellevue",
        "state": "WA",
        "zip": "98004",
        "country": "US",
        "phoneNumber": "000-000-0000"
      },
      "payment": {
        "creditCard": {
          "cardNumber": "4111111111111111",
          "expirationDate": "2023-12"
        }
      },
      "defaultPaymentProfile": false
    },
    "validationMode": "liveMode"
  }
}
```

As well as, if I use the package, first I need to get `Customer Payment Profile` over HTTP and then put that information into `authorizeNetToken()` callback

```dart
AuthorizeNetPlugin.authorizeNetToken(
          env: 'test',
          cardNumber: '370000000000002',
          expirationMonth: '02',
          expirationYear: '2022',
          cardCvv: '900',
          zipCode: '30028',
          cardHolderName: 'Jeremiah',
          apiLoginId: '7594xDmRz',
          clientId:
              '34Fg4ta24e5Y6VQ8guqgUKguPLxW7EwqWWd2wSzCjwDUTN65w9SZ2Qk3p95X93cs');
```

This defeats the whole purpose of using the package while using customer profiles. Because there is an API available to execute without putting the information again. [https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile](https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile)

```
{
    "createTransactionRequest": {
        "merchantAuthentication": {
            "name": "9bSaKC66uHg",
            "transactionKey": "8xszx7B7674QxHqe"
        },
        "refId": "123456",
        "transactionRequest": {
            "transactionType": "authCaptureTransaction",
            "amount": "45",
              "profile": {
    		  	"customerProfileId": "40338125",
    		  	"paymentProfile": { "paymentProfileId": "1000177237" }
  			},
            "lineItems": {
                "lineItem": {
                    "itemId": "1",
                    "name": "vase",
                    "description": "Cannes logo",
                    "quantity": "18",
                    "unitPrice": "45.00"
                }
            },
			"processingOptions": {
            "isSubsequentAuth": "true"
			},
			"subsequentAuthInformation": {
	             "originalNetworkTransId": "123456789123456",
	             "originalAuthAmount": "45.00",
	             "reason": "resubmission"
             
            },
			"authorizationIndicatorType": {
            "authorizationIndicator": "final"
            }
        }
    }
}
```

### My thoughts

 Because I want to keep app PCI compliant and don't want to send payment data over HTTP. I would like to use your package.

Can you please put some methods to execute creating customer profile and also charging it while using Under the hood SDK?

**Comment by jeremiahlukus** [comment]
Hey yes I think that is a good idea PR’s are open for this as well. Since this would be not just a wrapper if you do make this methods then it would need tests.

**Comment by UsamaKarim** [comment]
> Hey yes I think that is a good idea PR’s are open for this as well. Since this would be not just a wrapper if you do make this methods then it would need tests.

1. Does the official SDK (Android/iOS) supports managing customer profiles?
2. How are you managing customer profiles in your apps before while using the package?

**Comment by jeremiahlukus** [comment]
You can read the docs for the sdk’s as far as I know they just support the token. 

I have a database where I store the customer profile Id, customer payment id and subscription Id (if it’s a subscription). I went into more detail in the last issue you created. 

And this package (the auth net sdk’s) creates the token from your credit card information. It doesn’t store anything it just creates a token so you are not sending sensitive information.

**Comment by UsamaKarim** [comment]
> And this package (the auth net sdk’s) creates the token from your credit card information. It doesn’t store anything it just creates a token so you are not sending sensitive information.

I am confident about that but while creating customer profile we need to send sensitive data over HTTP

**Comment by jeremiahlukus** [comment]
The profile gets created on transaction

**Comment by jeremiahlukus** [comment]
So get the token create a transaction and the save the response

**Comment by UsamaKarim** [comment]
> So get the token create a transaction and the save the response

Unfortunately, Customer Profile is not getting created on my side.
I am getting following response
```
{transactionResponse: {responseCode: 1, authCode: 000000, avsResultCode: P, cvvResultCode: , cavvResultCode: , transId: 0, refTransID: , transHash: , testRequest: 1, accountNumber: XXXX0002, accountType: AmericanExpress, messages: [{code: 1, description: This transaction has been approved.}], transHashSha2: , SupplementalDataQualificationIndicator: 0}, refId: 123456, messages: {resultCode: Ok, message: [{code: I00001, text: Successful.}]}}
```
### The response example on Authorize documentation
```json
{
    "transactionResponse": {
        "responseCode": "1",
        "authCode": "HW617E",
        "avsResultCode": "Y",
        "cvvResultCode": "",
        "cavvResultCode": "",
        "transId": "2157047189",
        "refTransID": "",
        "transHash": "E7CEB0A9F1BECA32A02493E1B31D5955",
        "testRequest": "0",
        "accountNumber": "XXXX1111",
        "accountType": "Visa",
        "messages": [
            {
                "code": "1",
                "description": "This transaction has been approved."
            }
        ],
        "transHashSha2": "D0C4FFF5648511A5862B917CFD9BB78ABF8A6E1D90C119CBBC4C0B454F4FF40DED15B204E042F36ECA5FB15D02588E4E4A7B85B94E7279599CE6020462CB7DEE",
        "SupplementalDataQualificationIndicator": 0,
	"networkTransId": "123456789NNNH"
    },
    "messages": {
        "resultCode": "Ok",
        "message": [
            {
                "code": "I00001",
                "text": "Successful."
            }
        ]
    }
}
```
What should I save to access the customer profile?

**Comment by jeremiahlukus** [comment]
@UsamaKarim I am in no way associated with authorize net. I built this because client needed it. If there is n issue with the package i can fix that but i cant really help you build out your payment solution. This is just a wrapper around the android and ios sdk's. So whatever the sdk's do this package does. I think you should post these questions on the auth net form or file an issue on their sdk github.

**Comment by jeremiahlukus** [comment]
If there is an issue in the package id be more than happy to look into it. Im closing this since it really isnt an issue its how to implement authorize.net in your application.

**Comment by UsamaKarim** [comment]
> If there is an issue in the package id be more than happy to look into it. Im closing this since it really isnt an issue it's how to implement authorize.net in your application.

@jeremiahlukus 

I would be very happy to know how you implemented the payment system on your side. Not the whole payment system just the part of creating customer profiles using this package. I have no problem implementing payments in the app with Authorize API, as there is a package available from you (I really appreciate your contribution towards the community), I want to utilize your package and also make a contribution only if I could get a little help to not sending payments details over HTTP

I already planned to PR this functionality into the package.
