### ISSUE TITLE
 onErrorReceived should return error not success via method channel

### ISSUE THREAD

**Issue by Okiring** [jeremiahlukus/authorize_net_plugin#8]
This will always return success even when thea is an error.

`  @Override
  public void onErrorReceived(ErrorTransactionResponse errorResponse)
  {
    Message error = errorResponse.getFirstErrorMessage();
    System.out.println("::::::::::::::::::::::::");
    System.out.println( error.getMessageText());
    System.out.println("::::::::::::::::::::::::");
    if(channelResult!=null){
      channelResult.success(error.getMessageText());
    }
  }
`

This comes as success so the try/catch wont work when calling the AuthorizeNetPlugin.authorizeNetToken method

`I/System.out(23569): ::::::::::::::::::::::::
I/System.out(23569): failed to connect to apitest.authorize.net/198.241.206.22 (port 443) from /102.83.13.83 (port 33324) after 5000ms
I/System.out(23569): ::::::::::::::::::::::::`

**RECOMMENDED FIX**

 channelResult.error({replace_with_any_code},error.getMessageText(),null);

**Comment by jeremiahlukus** [comment]
Hey @Okiring  can you send a PR?

**Comment by Okiring** [comment]
Okay..will send my PR in a few hours. Working on the changes. Just gotten some free time.

**Comment by jeremiahlukus** [comment]
closed by https://github.com/jeremiahlukus/authorize_net_plugin/pull/9

**Comment by jeremiahlukus** [comment]
Successfully uploaded https://pub.dev/packages/authorize_net_plugin version 0.1.2.
